leftnav:
- identifier: ad751aab-5013-2a94-179a-6178da1a3084
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: fdca5c32-8c90-d528-abcd-96454a52e3f8
  name: Assignments
  pageRef: /pages/assignments
  weight: 20
- identifier: fa35d3fa-d074-d4bb-402e-8c1144fcb74e
  name: Study Materials
  pageRef: /pages/study-materials
  weight: 30
- identifier: 84186bbe-94e1-e986-a1d5-1e9c77cea261
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 40
- identifier: dab9df39-9bd5-5ad1-1320-b67e2c53e3fa
  name: Piano Lab
  pageRef: /pages/piano-lab
  weight: 50
